twist_mux:
  ros__parameters:
    topics:
      controller:
        topic   : controller_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100
